package at.ac.fhcampuswien.fhmdb.models;

public enum Genre {
    ALL, NONE, ACTION, ADVENTURE, ANIMATION, BIOGRAPHY, COMEDY, CRIME,
    DRAMA, DOCUMENTARY, FAMILY, FANTASY, HISTORY, HORROR, MUSICAL, MYSTERY,
    ROMANCE, SCIENCE_FICTION, SPORT, THRILLER, WAR, WESTERN
}
